---
title: "GapMinder-dplyr"
author: "Blake"
date: "19/06/2019"
output: html_document
---

Loading tidyverse

```{r}
library(tidyverse)
```

Load data

```{r}
gapminder <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")
```


Filter function (operates on rows)

```{r}
filter(gapminder, lifeExp < 29)

filter(gapminder, country == "Mexico")

filter(gapminder, country %in% c("Mexico", "Peru"))

filter(gapminder, country == "Mexico", year == 2002)

x <- filter(gapminder, country == "Brazil", year > 1986)  
mean(x$lifeExp)  

```


Select function (operates on columns)

```{r}
select(gapminder, year, country, lifeExp)

select(gapminder, -continent, -gdpPercap)

```

Select and filter together

```{r}

gap_cambodia <- filter(gapminder, country =="Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

```

Piping #andthen (%>%, CMD+SHIFT+M)

```{r}

gapminder %>% head()
head(gapminder)

gap_cambodia <- gapminder %>% 
  filter(country =="Cambodia") %>% 
  select(-continent, -lifeExp)

```

Mutate function (adds a new column)

```{r}

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

gapminder %>%
  filter(continent == "Asia",
         year == 2007) %>%
  mutate(pop_thousands = pop/1000)

```










