---
title: "Tidy Coral"
author: "Blake"
date: "19/06/2019"
output: html_document
---

```{r setup, warning=FALSE, message=FALSE}

library(tidyverse)
library(janitor)
library(skimr)
library(stringr)

## data filepaths/urls ----

## benthic data
benthic_url <- 'https://www.nodc.noaa.gov/archive/arc0054/0104255/1.1/data/0-data/cd08/100308OaAla03m.CSV'

## buoy data
buoy_url <- 'http://www.ndbc.noaa.gov/view_text_file.php?filename=mokh1h2010.txt.gz&dir=data/historical/stdmet/'

```

```{r benthic raw}
benthic_raw <- read_csv(benthic_url)
head(benthic_raw) 

```

#Wrangle

```{r wrangle}
#clean the variable names
benthic <- benthic_raw %>% 
  janitor::clean_names()

#select columns we need
benthic <- benthic %>%
  select(id_name, point, x, y, id_date) %>% 
  mutate(date = stringr::str_remove_all(id_date, "#"))

benthic  

```


```{r}
summary(benthic)

skimr::skim(benthic)

unique(benthic$id_name)

ggplot(benthic, aes(date, fill = id_name)) +
  geom_bar()

```


Buoy Data (import at .txt file for your data)

```{r}

buoy <- readr::read_table2(buoy_url)
head(buoy)

```

#Wrangle

```{r}
#overwrite column names
names(buoy) <- str_c(
  names(buoy),
  buoy %>% filter(`#YY` == "#yr"),
  sep = "_")

names(buoy) <- str_replace_all(names(buoy), "#", "")  # replace `#` with nothing 
names(buoy) <- str_replace_all(names(buoy), "/", "_") # replace `/` with `_`

#remove redundant row
buoy <- buoy %>%
  filter(YY_yr != "#yr")

```

```{r}
ggplot(buoy, aes(WTMP_degC)) +
  geom_bar()
```

#Join

```{r}
buoy <- buoy %>%
  unite(date, c(YY_yr, MM_mo, DD_dy), sep = "-")

bb_join <- benthic %>%
  left_join(buoy, by = "date")

head(bb_join) # kind of hard to see what's going on.
## let's select a few columns and inspect:
bb_join %>%
  select(id_name, x, y, date, hh_hr, mm_mn, WTMP_degC) %>%
  head()


```









